#! /bin/sh

case "$1" in
  start)
    mlflow ui --host 0.0.0.0 --file-store ./logs/mlruns &
  ;;
  stop)
    pkill -9 mlflow
    pkill -9 gunicorn
  ;;
  restart)
    pkill -9 mlflow
    pkill -9 gunicorn
    mlflow ui --host 0.0.0.0 --file-store ./logs/mlruns
  ;;
  status)
    ps -ef|grep -i -E "[m]lflow|[g]unicorn"
    ;;
  *)
    echo "Usage: /etc/init.d/$NAME {start|stop|restart|status}" >&2
    exit 2
  ;;
esac
